#!/usr/bin/env python3
"""Flag example sentences whose `en` translation doesn't faithfully match `jp`.

`examples.en` is LLM-generated by the same step that produces `jp`/`jp_reading`
(build_db.py's compute_row). Some of these translations are wrong — see
docs/translation_qc.md. This sends each (jp, en) pair to a judge model and
flags pairs where the judge thinks the translation is inaccurate.

Deliberately uses a different model family than the generator (build_db.py's
default is Qwen3.6-35B) to avoid the generator rubber-stamping its own
mistakes — default judge is Gemini 2.5 Flash via OpenRouter.

Resumable via `examples.translation_check_status`, same pattern as the other
per-row enrichment scripts.
"""
import argparse
import json
import os
import re
import sqlite3
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

import requests

from build_db import OPENROUTER_URL, extract_json

MAX_ATTEMPTS_DEFAULT = 3
DEFAULT_MODEL = "google/gemini-2.5-flash"
JUDGE_MAX_TOKENS = 150


def ensure_columns(conn):
    cols = {row[1] for row in conn.execute("PRAGMA table_info(examples)")}
    if "translation_mismatch" not in cols:
        conn.execute("ALTER TABLE examples ADD COLUMN translation_mismatch INTEGER NOT NULL DEFAULT 0")
    if "translation_issue" not in cols:
        conn.execute("ALTER TABLE examples ADD COLUMN translation_issue TEXT")
    if "translation_check_status" not in cols:
        conn.execute("ALTER TABLE examples ADD COLUMN translation_check_status TEXT NOT NULL DEFAULT 'pending'")
    if "translation_check_attempts" not in cols:
        conn.execute("ALTER TABLE examples ADD COLUMN translation_check_attempts INTEGER NOT NULL DEFAULT 0")
    if "translation_check_error" not in cols:
        conn.execute("ALTER TABLE examples ADD COLUMN translation_check_error TEXT")
    conn.commit()


def build_prompt(jp, en):
    return f"""You are a Japanese-to-English translation QC judge. Check whether the English translation accurately conveys the meaning of the Japanese sentence — same facts, same subject/object relationships, no added or dropped meaning. Minor natural phrasing differences are fine; only flag actual mistranslations.

Japanese: {jp}
English: {en}

Respond with ONLY a JSON object (no markdown, no commentary):
{{"faithful": true or false, "issue": "<one short sentence describing the mistranslation, or null if faithful>"}}
"""


def call_judge(model, prompt, timeout=60):
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        raise RuntimeError("OPENROUTER_API_KEY not set in environment")
    resp = requests.post(
        OPENROUTER_URL,
        headers={"Authorization": f"Bearer {api_key}"},
        json={
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "response_format": {"type": "json_object"},
            "max_tokens": JUDGE_MAX_TOKENS,
            "temperature": 0,
        },
        timeout=timeout,
    )
    resp.raise_for_status()
    data = resp.json()
    if "error" in data:
        raise RuntimeError(f"openrouter error: {data['error']}")
    content = data["choices"][0]["message"]["content"]
    return extract_json(content)


def compute_row(model, row, timeout=60):
    """Network work only, no DB access — safe to run from worker threads."""
    row_id = row["id"]
    try:
        prompt = build_prompt(row["jp"], row["en"])
        result = call_judge(model, prompt, timeout=timeout)
        faithful = result.get("faithful")
        if not isinstance(faithful, bool):
            raise ValueError(f"missing/invalid 'faithful' field: {result!r}")
        issue = result.get("issue") if not faithful else None
        return {"id": row_id, "ok": True, "mismatch": not faithful, "issue": issue}
    except Exception as e:
        return {"id": row_id, "ok": False, "error": str(e)[:500]}


def persist_result(conn, row, result, max_attempts):
    """DB writes only — call from the main thread to keep sqlite single-writer."""
    row_id = result["id"]
    if result["ok"]:
        conn.execute(
            "UPDATE examples SET translation_mismatch = ?, translation_issue = ?, "
            "translation_check_status = 'done', translation_check_error = NULL WHERE id = ?",
            (int(result["mismatch"]), result["issue"], row_id),
        )
    else:
        attempts = row["translation_check_attempts"] + 1
        status = "failed" if attempts >= max_attempts else "error"
        conn.execute(
            "UPDATE examples SET translation_check_status = ?, translation_check_attempts = ?, "
            "translation_check_error = ? WHERE id = ?",
            (status, attempts, result["error"], row_id),
        )
    conn.commit()


def main():
    ap = argparse.ArgumentParser(description="Flag example translations where the judge model disagrees with `en`.")
    ap.add_argument("--db", default="vocab.db")
    ap.add_argument("--model", default=DEFAULT_MODEL, help="OpenRouter judge model")
    ap.add_argument("--max-attempts", type=int, default=MAX_ATTEMPTS_DEFAULT)
    ap.add_argument("--limit", type=int, default=None, help="only process N rows (testing)")
    ap.add_argument("--workers", type=int, default=1, help="parallel judge requests in flight")
    ap.add_argument("--timeout", type=int, default=60, help="per-request timeout in seconds")
    ap.add_argument("--retry-backoff", type=float, default=3.0, help="seconds to wait before retrying errored rows")
    args = ap.parse_args()

    if not os.environ.get("OPENROUTER_API_KEY"):
        sys.exit("OPENROUTER_API_KEY not set in environment")

    conn = sqlite3.connect(args.db)
    conn.row_factory = sqlite3.Row
    ensure_columns(conn)

    pending = conn.execute(
        "SELECT * FROM examples WHERE translation_check_status IN ('pending', 'error') ORDER BY id"
    ).fetchall()
    if args.limit:
        pending = pending[: args.limit]
    target_ids = [r["id"] for r in pending]
    total = len(target_ids)
    print(f"{total} examples to judge (model={args.model}, workers={args.workers})")

    t0 = time.time()
    n_done = 0
    round_num = 0
    while True:
        round_num += 1
        if not target_ids:
            break
        placeholders = ",".join("?" * len(target_ids))
        batch = conn.execute(
            f"SELECT * FROM examples WHERE id IN ({placeholders}) AND translation_check_status IN ('pending', 'error') "
            f"AND translation_check_attempts < ? ORDER BY id",
            (*target_ids, args.max_attempts),
        ).fetchall()
        if not batch:
            break
        if round_num > 1:
            print(f"-- retry round {round_num}: {len(batch)} row(s) --", file=sys.stderr)
            time.sleep(args.retry_backoff)

        with ThreadPoolExecutor(max_workers=args.workers) as ex:
            futures = {
                ex.submit(compute_row, args.model, row, args.timeout): row
                for row in batch
            }
            for fut in as_completed(futures):
                row = futures[fut]
                result = fut.result()
                persist_result(conn, row, result, args.max_attempts)
                if result["ok"]:
                    n_done += 1
                    tag = "MISMATCH" if result["mismatch"] else "ok"
                    if result["mismatch"]:
                        tag += f" ({result['issue']})"
                else:
                    attempts = row["translation_check_attempts"] + 1
                    will_retry = attempts < args.max_attempts
                    tag = f"{'ERROR, will retry' if will_retry else 'FAILED'} ({result['error']})"
                    if not will_retry:
                        n_done += 1
                elapsed = time.time() - t0
                rate = n_done / elapsed if elapsed > 0 else 0
                eta = (total - n_done) / rate if rate > 0 else float("inf")
                print(
                    f"[{n_done}/{total}] id={row['id']} word_rank={row['word_rank']} -> {tag}  (eta {eta/60:.1f}m)",
                    file=sys.stderr,
                )

    final = conn.execute(
        "SELECT translation_check_status, count(*) c FROM examples GROUP BY translation_check_status"
    ).fetchall()
    summary = {r["translation_check_status"]: r["c"] for r in final}
    flagged = conn.execute("SELECT count(*) FROM examples WHERE translation_mismatch = 1").fetchone()[0]
    print(f"summary: {summary} flagged mismatches={flagged}")


if __name__ == "__main__":
    main()
